services:
  web:
    build: .
    ports:
      - "4545:4545"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      DB_HOST: "${DB_SERVER}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USERNAME}"
      DB_PASS: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    command: python prod.py
