[tool.taskipy.tasks]
dev = "uvicorn src.main:app --host 0.0.0.0 --port 4545 --reload"
prod = "python prod.py"
install = "pip install -r requirements.txt"
servicesUp = "docker compose up -d --build"
test = "set PYTHONPATH=src && python -m pytest -q src/tests/processes/router_test.py -v"
testWatch = "set PYTHONPATH=src && ptw --runner \"python -m pytest -q src/tests\""
lintCheck = "ruff check ."
lintFix = "ruff check . --fix"

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
