[tool.taskipy.tasks]
dev = "uvicorn src.main:app --reload"
install = "pip install -r requirements.txt"
test = "set PYTHONPATH=src && python -m pytest -q src/tests/processes/router_test.py -v"
testWatch = "set PYTHONPATH=src && ptw --runner \"python -m pytest -q src/tests\""

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I"]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
